services:
  pet:
    build: .
    environment:
      - MONGO_DB_URL=mongodb://docker.for.mac.host.internal/local
    env_file:
      - .env
    ports:
      - 3000:3000
  mongodb:
      image: mongo:6-jammy
      ports:
        - '27017:27017'
      volumes:
        - petdb:/data/db
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
volumes:
  petdb: